# This workflow builds the project, then runs the linter, and runs all tests.

name: Node.js CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  NODE_VERSION: 22

jobs:
  ci:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v4
    
    - name: Use Node.js ${{ env.NODE_VERSION }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ env.NODE_VERSION }}
        cache: 'npm'
        
    - name: Install dependencies
      run: npm ci

    - name: Build project
      run: npm run build --if-present

    - name: Lint project
      run: npm run lint
        
    # - name: Run tests
    #   run: npm run test
